# Generated by Django 5.0.2 on 2025-02-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='attend',
        ),
        migrations.AddField(
            model_name='event',
            name='attend',
            field=models.ManyToManyField(blank=True, to='event.myuser'),
        ),
    ]
