# Generated by Django 5.0.2 on 2025-02-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_remove_myuser_attend_event_attend'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='manager',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
