# Generated by Django 5.0.2 on 2025-02-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_vanue_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='vanue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
