# Generated by Django 5.0.2 on 2025-02-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_vanue_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='aproved',
            field=models.BooleanField(default=False),
        ),
    ]
